import 'package:flutter/material.dart';
import 'package:parachute/core/theme/design_tokens.dart';

/// Wrapper for compact summary messages (auto-generated by Claude SDK)
///
/// These messages represent compacted conversation history and should
/// be collapsed by default to reduce visual clutter.
class CollapsibleCompactSummary extends StatefulWidget {
  /// The child widget(s) to show when expanded
  final Widget child;
  final bool isDark;

  /// Whether the section should start expanded (default: false for compact summaries)
  final bool initiallyExpanded;

  /// Preview text to show in the collapsed header
  final String? previewText;

  const CollapsibleCompactSummary({
    super.key,
    required this.child,
    required this.isDark,
    this.initiallyExpanded = false,
    this.previewText,
  });

  @override
  State<CollapsibleCompactSummary> createState() => _CollapsibleCompactSummaryState();
}

class _CollapsibleCompactSummaryState extends State<CollapsibleCompactSummary> {
  late bool _isExpanded;

  @override
  void initState() {
    super.initState();
    _isExpanded = widget.initiallyExpanded;
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Collapsed header (always visible)
        GestureDetector(
          onTap: () => setState(() => _isExpanded = !_isExpanded),
          child: Container(
            margin: EdgeInsets.only(
              left: Spacing.md,
              right: Spacing.md,
              top: Spacing.sm,
              bottom: _isExpanded ? Spacing.xs : Spacing.sm,
            ),
            padding: const EdgeInsets.symmetric(
              horizontal: Spacing.sm,
              vertical: Spacing.xs,
            ),
            decoration: BoxDecoration(
              color: widget.isDark
                  ? BrandColors.nightSurface.withValues(alpha: 0.4)
                  : BrandColors.cream.withValues(alpha: 0.6),
              borderRadius: BorderRadius.circular(Radii.sm),
              border: Border.all(
                color: widget.isDark
                    ? BrandColors.nightTextSecondary.withValues(alpha: 0.2)
                    : BrandColors.driftwood.withValues(alpha: 0.2),
                width: 0.5,
              ),
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(
                  _isExpanded ? Icons.expand_less : Icons.expand_more,
                  size: 16,
                  color: widget.isDark
                      ? BrandColors.nightTextSecondary
                      : BrandColors.driftwood,
                ),
                const SizedBox(width: Spacing.xs),
                Icon(
                  Icons.auto_awesome_outlined,
                  size: 14,
                  color: widget.isDark
                      ? BrandColors.nightTextSecondary
                      : BrandColors.driftwood,
                ),
                const SizedBox(width: Spacing.xs),
                Text(
                  'Conversation summary',
                  style: TextStyle(
                    color: widget.isDark
                        ? BrandColors.nightTextSecondary
                        : BrandColors.driftwood,
                    fontSize: TypographyTokens.labelSmall,
                    fontStyle: FontStyle.italic,
                  ),
                ),
                if (widget.previewText != null && !_isExpanded) ...[
                  const SizedBox(width: Spacing.sm),
                  Flexible(
                    child: Text(
                      widget.previewText!,
                      style: TextStyle(
                        color: widget.isDark
                            ? BrandColors.nightTextSecondary.withValues(alpha: 0.7)
                            : BrandColors.driftwood.withValues(alpha: 0.7),
                        fontSize: TypographyTokens.labelSmall,
                      ),
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                    ),
                  ),
                ],
              ],
            ),
          ),
        ),
        // Expanded content
        if (_isExpanded) widget.child,
      ],
    );
  }
}
